# Generated by Django 4.2 on 2026-01-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'HR'), ('Engineering', 'Engineering'), ('Sales', 'Sales')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst')], max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
